@extends('panel.layout')
@section('title', 'Pengaturan Payment Gateway')
@section('content')

<div class="max-w-4xl mx-auto space-y-8">

<div>
    <h2 class="text-2xl font-bold text-gray-900">💳 Payment Gateway</h2>
    <p class="text-sm text-gray-500 mt-1">Konfigurasi provider pembayaran untuk booking engine. Pilih provider, isi kredensial, dan simpan.</p>
</div>

{{-- Provider List --}}
<div x-data="paymentSettings()" class="space-y-6">

    {{-- Add New Provider --}}
    <div class="bg-white rounded-2xl shadow-card border border-gray-100 p-6">
        <h3 class="text-sm font-semibold text-gray-700 mb-4">Tambah Provider Baru</h3>

        {{-- Step 1: Select Provider --}}
        <div class="mb-4">
            <label class="block text-xs font-semibold text-gray-600 mb-1.5">Pilih Provider</label>
            <select x-model="selectedPreset" @change="onPresetChange()"
                    class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900 focus:bg-white focus:border-primary-400 focus:ring-2 focus:ring-primary-100 transition-all outline-none">
                <option value="">-- Pilih Payment Gateway --</option>
                @foreach($presets as $preset)
                    <option value="{{ $preset['name'] }}">{{ $preset['name'] }}</option>
                @endforeach
            </select>
        </div>

        {{-- Step 2: Dynamic Fields (Alpine.js driven) --}}
        <template x-if="selectedPreset">
            <div>
                {{-- Provider Info Card --}}
                <div class="bg-indigo-50 border border-indigo-200 rounded-xl p-4 mb-5 text-sm">
                    <template x-if="currentPreset">
                        <div class="flex flex-wrap items-center gap-3">
                            <span class="font-bold text-indigo-700" x-text="currentPreset.name"></span>
                            <span class="text-indigo-300">|</span>
                            <span class="text-slate-600">Format: <span class="font-mono text-xs bg-indigo-100 px-2 py-0.5 rounded" x-text="currentPreset.api_format"></span></span>
                            <span class="text-indigo-300">|</span>
                            <span class="text-slate-600">
                                Mendukung:
                                <span class="text-xs" x-text="currentPreset.supported_methods.join(', ')"></span>
                            </span>
                            <template x-if="currentPreset.documentation_url">
                                <a :href="currentPreset.documentation_url" target="_blank" class="text-indigo-600 hover:underline ml-auto text-xs">📖 Dokumentasi API →</a>
                            </template>
                        </div>
                    </template>
                </div>

                {{-- Dynamic Form Fields --}}
                <form method="POST" action="{{ route('panel.settings.payments.store') }}" class="space-y-4">
                    @csrf
                    <input type="hidden" name="provider_name" x-bind:value="selectedPreset">
                    <input type="hidden" name="api_format" x-bind:value="currentPreset?.api_format">
                    <input type="hidden" name="base_url" x-bind:value="currentPreset?.base_url">

                    {{-- Provider Name --}}
                    <div>
                        <label class="block text-xs font-semibold text-gray-600 mb-1.5">Nama Provider</label>
                        <input type="text" x-bind:value="selectedPreset" readonly
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-500">
                    </div>

                    {{-- Dynamic fields generated by Alpine.js --}}
                    <template x-for="field in currentPreset?.fields" :key="field.key">
                        <div>
                            <label class="block text-xs font-semibold text-gray-600 mb-1.5">
                                <span x-text="field.label"></span>
                                <span x-show="field.required" class="text-red-500">*</span>
                            </label>

                            {{-- Password field --}}
                            <template x-if="field.type === 'password'">
                                <div x-data="{ show: false }" class="relative">
                                    <input :type="show ? 'text' : 'password'"
                                           :name="'fields[' + field.key + ']'"
                                           :required="field.required"
                                           :placeholder="field.placeholder"
                                           class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 pr-12 text-sm font-mono focus:bg-white focus:border-primary-400 focus:ring-2 focus:ring-primary-100 transition-all outline-none">
                                    <button type="button" @click="show = !show"
                                            class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                                        <svg x-show="!show" class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                                        <svg x-show="show" class="w-5 h-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M15 12a3 3 0 01-6 0m0 0a3 3 0 016 0"/></svg>
                                    </button>
                                </div>
                            </template>

                            {{-- Text field --}}
                            <template x-if="field.type === 'text'">
                                <input type="text"
                                       :name="'fields[' + field.key + ']'"
                                       :required="field.required"
                                       :placeholder="field.placeholder"
                                       class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm focus:bg-white focus:border-primary-400 focus:ring-2 focus:ring-primary-100 transition-all outline-none">
                            </template>

                            {{-- Toggle --}}
                            <template x-if="field.type === 'toggle'">
                                <label class="inline-flex items-center gap-3 cursor-pointer">
                                    <input type="hidden" :name="'fields[' + field.key + ']'" value="0">
                                    <input type="checkbox" :name="'fields[' + field.key + ']'" value="1"
                                           class="rounded border-gray-300 text-primary-600 focus:ring-primary-400">
                                    <span class="text-sm text-gray-600">Aktifkan mode production (jangan centang untuk sandbox)</span>
                                </label>
                            </template>
                        </div>
                    </template>

                    {{-- Base URL Override --}}
                    <div>
                        <label class="block text-xs font-semibold text-gray-600 mb-1.5">
                            Base URL <span class="text-xs text-gray-400 font-normal">(opsional — override URL default)</span>
                        </label>
                        <input type="text" name="custom_base_url"
                               x-bind:placeholder="currentPreset?.sandbox_url || currentPreset?.base_url"
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm font-mono focus:bg-white focus:border-primary-400 focus:ring-2 focus:ring-primary-100 transition-all outline-none">
                    </div>

                    {{-- Submit --}}
                    <div class="flex items-center gap-3 pt-2">
                        <button type="submit"
                                class="inline-flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white text-sm font-semibold px-5 py-2.5 rounded-xl shadow-sm transition-colors">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>
                            Simpan & Aktifkan
                        </button>
                    </div>
                </form>
            </div>
        </template>

        {{-- Empty state --}}
        <template x-if="!selectedPreset">
            <div class="text-center py-8 text-gray-400">
                <span class="text-5xl block mb-3">💳</span>
                <p>Pilih payment gateway dari dropdown di atas untuk mulai konfigurasi.</p>
                <p class="text-xs mt-1">13 provider tersedia — Midtrans, Xendit, DOKU, iPaymu, dan lainnya.</p>
            </div>
        </template>
    </div>

    {{-- Existing Providers Table --}}
    @if($providers->isNotEmpty())
    <div class="bg-white rounded-2xl shadow-card border border-gray-100 overflow-hidden">
        <div class="px-5 py-4 border-b border-gray-50 flex items-center justify-between">
            <h3 class="text-sm font-semibold text-gray-700">Provider Terpasang</h3>
            <span class="text-xs text-gray-400">{{ $providers->count() }} provider</span>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead>
                    <tr class="bg-gray-50/80 border-b border-gray-100">
                        <th class="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Provider</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Format</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Metode</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wide">Status</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wide">Test</th>
                        <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Aksi</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-50">
                    @foreach($providers as $provider)
                    <tr class="hover:bg-gray-50/60 transition-colors">
                        <td class="px-5 py-3.5">
                            <div class="flex items-center gap-3">
                                <div class="w-8 h-8 rounded-lg bg-emerald-50 flex items-center justify-center shrink-0">
                                    <span class="text-xs font-bold text-emerald-600">PAY</span>
                                </div>
                                <div>
                                    <div class="text-sm font-medium text-gray-900">{{ $provider->name }}</div>
                                    @if($provider->is_default)
                                    <span class="text-xs text-primary-600 font-medium">Default</span>
                                    @endif
                                </div>
                            </div>
                        </td>
                        <td class="px-4 py-3.5 text-xs text-gray-500 font-mono">{{ $provider->api_format }}</td>
                        <td class="px-4 py-3.5">
                            @php
                                $methods = $provider->capabilities['supported_methods'] ?? ($provider->extra_config['supported_methods'] ?? []);
                            @endphp
                            <div class="flex flex-wrap gap-1">
                                @foreach(array_slice((array)$methods, 0, 4) as $m)
                                    <span class="text-[10px] bg-gray-100 text-gray-600 px-1.5 py-0.5 rounded-full">{{ str_replace('_', ' ', $m) }}</span>
                                @endforeach
                                @if(count($methods) > 4)
                                    <span class="text-[10px] text-gray-400">+{{ count($methods) - 4 }}</span>
                                @endif
                            </div>
                        </td>
                        <td class="px-4 py-3.5 text-center">
                            @if($provider->is_active)
                            <span class="inline-flex items-center gap-1 text-xs bg-emerald-50 text-emerald-700 px-2 py-0.5 rounded-full font-medium">
                                <span class="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> Aktif
                            </span>
                            @else
                            <span class="inline-flex items-center gap-1 text-xs bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full font-medium">
                                <span class="w-1.5 h-1.5 rounded-full bg-gray-400"></span> Nonaktif
                            </span>
                            @endif
                        </td>
                        <td class="px-4 py-3.5 text-center">
                            @php $ts = $provider->test_status ?? 'untested'; @endphp
                            <span class="text-xs px-2 py-0.5 rounded-full font-medium {{ $ts === 'ok' ? 'bg-emerald-50 text-emerald-700' : ($ts === 'failed' ? 'bg-red-50 text-red-600' : 'bg-gray-100 text-gray-500') }}">
                                {{ $ts === 'ok' ? 'OK' : ($ts === 'failed' ? 'Gagal' : 'Belum') }}
                            </span>
                        </td>
                        <td class="px-4 py-3.5">
                            <div class="flex items-center gap-1 justify-end">
                                <form method="POST" action="{{ route('panel.settings.integrations.test', $provider->id) }}" class="inline">
                                    @csrf
                                    <button type="submit" class="text-xs font-medium text-primary-600 hover:text-primary-800 bg-primary-50 hover:bg-primary-100 px-2.5 py-1 rounded-lg transition-colors">Tes</button>
                                </form>
                                <form method="POST" action="{{ route('panel.settings.payments.toggle', $provider->id) }}" class="inline">
                                    @csrf @method('PATCH')
                                    <button class="text-xs font-medium {{ $provider->is_active ? 'text-amber-600 hover:bg-amber-50' : 'text-emerald-600 hover:bg-emerald-50' }} px-2.5 py-1 rounded-lg transition-colors">
                                        {{ $provider->is_active ? 'Nonaktifkan' : 'Aktifkan' }}
                                    </button>
                                </form>
                                <form method="POST" action="{{ route('panel.settings.payments.destroy', $provider->id) }}" class="inline" onsubmit="return confirm('Hapus provider ini?')">
                                    @csrf @method('DELETE')
                                    <button class="text-xs font-medium text-red-600 hover:text-red-800 bg-red-50 hover:bg-red-100 px-2.5 py-1 rounded-lg transition-colors">Hapus</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    @endif
</div>

</div>

<script>
function paymentSettings() {
    return {
        selectedPreset: '',
        currentPreset: null,
        presets: @json($presets),

        onPresetChange() {
            this.currentPreset = this.presets.find(p => p.name === this.selectedPreset) || null;
        }
    };
}
</script>
@endsection
